* **Конфигурирование**:

  Если вы хоть раз задавались вопросом, что означают различные опции в
  ваших конфигурационных файлах, таких как ``app/config/config.yml``, то
  этот раздел для вас. Здесь все конфигурационные параметры разбиты
  на подразделы по ключу (например ``framework``), которые определяют
  все возможные секции в настройках Symfony2.

  * :doc:`framework </reference/configuration/framework>`
  * :doc:`doctrine </reference/configuration/doctrine>`
  * :doc:`security </reference/configuration/security>`
  * :doc:`assetic </reference/configuration/assetic>`
  * :doc:`swiftmailer </reference/configuration/swiftmailer>`
  * :doc:`twig </reference/configuration/twig>`
  * :doc:`monolog </reference/configuration/monolog>`
  * :doc:`web_profiler </reference/configuration/web_profiler>`

* **Формы и валидация**

  * :doc:`Form Field Type Reference</reference/forms/types>`
  * :doc:`Validation Constraints Reference </reference/constraints>`
  * :doc:`Twig Template Function Reference</reference/forms/twig_reference>`

* **Остальные разделы**

  * :doc:`/reference/dic_tags`
  * :doc:`/reference/YAML`
  * :doc:`/reference/requirements`
