* **Шаблоны**:

  * `Twig`_ |
  * :doc:`PHP </guides/templating/PHP>` |
  * :doc:`Рецепты </guides/templating/recipes>`

* **Doctrine**:

  * :doc:`DBAL </guides/doctrine/dbal/overview>` |
  * :doc:`ORM </guides/doctrine/orm/overview>` |
  * :doc:`Migrations </guides/doctrine/migrations/overview>` |
  * :doc:`MongoDB </guides/doctrine/mongodb-odm/overview>`

* **Тестирование**:

  * :doc:`Обзор </guides/testing/overview>` |
  * :doc:`Настройка </guides/testing/configuration>` |
  * :doc:`Crawler </guides/testing/crawler>` |
  * :doc:`Client </guides/testing/client>` |
  * :doc:`Рецепты </guides/testing/recipes>`

* **Валидация**:

  * :doc:`Обзор </guides/validator/overview>` |
  * :doc:`Проверка </guides/validator/validation>` |
  * :doc:`Исключения </guides/validator/constraints>`

* **Формы**:

  * :doc:`Обзор </guides/forms/overview>` |
  * :doc:`Шаблоны </guides/forms/view>`

* **Безопасность**:

  * :doc:`Обзор </guides/security/overview>` |
  * :doc:`Пользователи </guides/security/users>` |
  * :doc:`Идентификация </guides/security/authentication>` |
  * :doc:`Авторизация </guides/security/authorization>`

* **Кэширование**:

  * :doc:`/guides/cache/http`

* :doc:`/guides/emails`
* :doc:`/guides/translation`
* **Диспетчер событий**:

  * :doc:`Обзор </guides/event/overview>` |
  * :doc:`Рецепты </guides/event/recipes>`

* **Инструменты**:

  * :doc:`/guides/tools/autoloader` |
  * :doc:`Finder </guides/tools/finder>` |
  * :doc:`/guides/tools/YAML` |
  * :doc:`Process </guides/tools/process>`

* **Бандлы**:

  * :doc:`Наилучшее применение </guides/bundles/best_practices>` |
  * :doc:`Настройка </guides/bundles/configuration>`

* **Внедрение зависимости**:

  * :doc:`Расширения </guides/dependency_injection/extensions>`

* **Внутренности**:

  * :doc:`Обзор </guides/internals/overview>` |
  * :doc:`Ядро </guides/internals/kernel>` |
  * :doc:`Profiler </guides/internals/profiler>`

* :doc:`Symfony2 для пользователей symfony 1</guides/symfony1>`
* :doc:`Symfony2 стабильный API</guides/stable_api>`

.. _Twig: http://www.twig-project.org/documentation
