Базовые ограничения
~~~~~~~~~~~~~~~~~~~

Ниже перечислены базовые ограничения: они используются для самых
простых проверок полей классов или значений, возвращаемых методами
объектов.

* :doc:`NotBlank </reference/constraints/NotBlank>`
* :doc:`Blank </reference/constraints/Blank>`
* :doc:`NotNull </reference/constraints/NotNull>`
* :doc:`Null </reference/constraints/Null>`
* :doc:`True </reference/constraints/True>`
* :doc:`False </reference/constraints/False>`
* :doc:`Type </reference/constraints/Type>`

Строковые ограничения
~~~~~~~~~~~~~~~~~~~~~

* :doc:`Email </reference/constraints/Email>`
* :doc:`MinLength </reference/constraints/MinLength>`
* :doc:`MaxLength </reference/constraints/MaxLength>`
* :doc:`Url </reference/constraints/Url>`
* :doc:`Regex </reference/constraints/Regex>`
* :doc:`Ip </reference/constraints/Ip>`

Числовые ограничения
~~~~~~~~~~~~~~~~~~~~

* :doc:`Max </reference/constraints/Max>`
* :doc:`Min </reference/constraints/Min>`

Ограничения дат
~~~~~~~~~~~~~~~

* :doc:`Date </reference/constraints/Date>`
* :doc:`DateTime </reference/constraints/DateTime>`
* :doc:`Time </reference/constraints/Time>`

Ограничения коллекций
~~~~~~~~~~~~~~~~~~~~~

* :doc:`Choice </reference/constraints/Choice>`
* :doc:`Collection </reference/constraints/Collection>`
* :doc:`UniqueEntity </reference/constraints/UniqueEntity>`
* :doc:`Language </reference/constraints/Language>`
* :doc:`Locale </reference/constraints/Locale>`
* :doc:`Country </reference/constraints/Country>`

Ограничения файлов
~~~~~~~~~~~~~~~~~~

* :doc:`File </reference/constraints/File>`
* :doc:`Image </reference/constraints/Image>`

Прочие ограничения
~~~~~~~~~~~~~~~~~~

* :doc:`Callback </reference/constraints/Callback>`
* :doc:`All </reference/constraints/All>`
* :doc:`UserPassword </reference/constraints/UserPassword>`
* :doc:`Valid </reference/constraints/Valid>`

.. toctree::
    :hidden:

    Translation source: 2011-09-30 283b2f5
    Corrected from:
