* **Код**:

  * :doc:`Ошибки </contributing/code/bugs>` |
  * :doc:`Патчи </contributing/code/patches>` |
  * :doc:`Безопасность </contributing/code/security>` |
  * :doc:`Тесты </contributing/code/tests>` |
  * :doc:`Правила написания кода </contributing/code/standards>` |
  * :doc:`Договорённости по коду </contributing/code/conventions>` |
  * :doc:`Лицензия </contributing/code/license>`

* **Документация**:

  * :doc:`Обзор </contributing/documentation/overview>` |
  * :doc:`Формат </contributing/documentation/format>` |
  * :doc:`Переводы </contributing/documentation/translations>` |
  * :doc:`Лицензия </contributing/documentation/license>`

* **Сообщество**:

  * :doc:`Совещения в IRC </contributing/community/irc>` |
  * :doc:`Другие источники </contributing/community/other>`
